# Generated by Django 5.1.4 on 2024-12-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_carta_poema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carta',
            name='etiquetas',
        ),
        migrations.AlterField(
            model_name='carta',
            name='imagen',
            field=models.URLField(blank=True, default='defaultImg.jpg', null=True),
        ),
    ]
