# Generated by Django 5.1.4 on 2024-12-30 06:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_carta_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
