# Generated by Django 5.1.4 on 2024-12-30 20:01

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_carta_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='contenido',
            field=django_quill.fields.QuillField(),
        ),
    ]
