# Generated by Django 5.1.4 on 2024-12-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_carta_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='carta',
            name='titulo',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
