# Generated by Django 5.1.4 on 2024-12-30 21:30

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_carta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='contenido',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='carta',
            name='imagen',
            field=models.URLField(blank=True, default='defaultImg.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='carta',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
