# Generated by Django 5.1.4 on 2024-12-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_carta_contenido_alter_carta_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='imagen',
            field=models.URLField(blank=True, default='https://i.pinimg.com/736x/9d/de/85/9dde859d52011fbb9f157516b1c77925.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='carta',
            name='titulo',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
