# Generated by Django 5.1.4 on 2024-12-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_carta_imagen_alter_carta_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ciudade',
            field=models.TextField(default='ciudad'),
        ),
    ]
