# Generated by Django 5.1.4 on 2024-12-31 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_profile_ciudade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ciudade',
            new_name='ciudad',
        ),
    ]
