# Generated by Django 5.1.4 on 2024-12-31 22:20

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_ciudade_profile_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poema',
            name='contenido',
            field=django_quill.fields.QuillField(),
        ),
    ]
