# Generated by Django 5.1.4 on 2024-12-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_poema_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poema',
            name='imagen',
            field=models.URLField(blank=True, default='https://i.pinimg.com/736x/65/74/65/657465bbe8aeaee85e0a4b73ca557731.jpg', null=True),
        ),
    ]
