# Generated by Django 5.1.4 on 2024-12-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_poema_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poema',
            name='titulo',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
