# Generated by Django 5.1.4 on 2025-01-02 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_poema_titulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('contenido', models.TextField()),
                ('fecha', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linea', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
